seed: 42
device: "cpu"  # cpu or cuda

input:
  path: datasets
  batch_size: 100


model:
  peer_normalization: 0.03
  momentum: 0.0  # Momentum to use for the running mean in peer normalization loss. It controls how much of the previous mean should be retained. A high momentum value gives more weight to the previous mean, while a lower value gives more weight to the current batch's mean activity. In the LoeweX implementation, the momentum is set to 0.9.

  hidden_dim: 1000
  num_layers: 3


training:
  epochs: 100

  learning_rate: 1e-3
  weight_decay: 3e-4
  momentum: 0.9

  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3

  val_idx: 1  # -1: validate only once training has finished; n: validate every n epochs.
  final_test: False  # Set to true to evaluate performance on test-set.


hydra:
  run:
    dir: logs